### ISSUE TITLE
Python 3.13 support?

### ISSUE THREAD

**Issue by aubreyyan** [HansBug/hbutils#111]
telnetlib was removed in python 3.13 which means this package is unusable for people on higher python versions. Can we remove our reliance on telnetlib?

**Comment by chef88314** [comment]
The `telnetlib` module allows you to interact with remote devices via the Telnet protocol, execute commands, and receive responses. This is useful in scenarios such as automating network device configuration and remote server management.
But there won't be telnetlib after python 3.13, maybe we need to degrade our python to lower version(lol)

**Comment by 202301060229** [comment]
According to the search results, since Python version 3.11, the `telnetlib` module has been deprecated and removed in version 3.13. This means that if you are using Python 3.11 or later, you will not be able to use the `telnetlib` module.
Use third-party libraries:
You can choose to use third-party libraries such as `telnetlib3` or `Exscript` instead of `telnetlib`. These libraries can be found on PyPI and can be installed through `pip`. For example, use `telnetlib3` to install `telnetlib3`.
Programming with socket:
If you don't want to rely on third-party libraries, you can use Python's `socket` module to implement the Telnet client function. 
Consider using other protocols:
If possible, consider using more modern and secure protocols such as SSH as an alternative to Telnet. Python's `paramiko` library provides SSH client and server functions and can be used as a secure alternative to Telnet.
With the above methods, you can gradually eliminate your dependence on `telnetlib` and migrate to a more modern and secure solution.

**Comment by aubreyyan** [comment]
@202301060229 what’s the point you’re trying to make in this issue? I have already established that telnetlib is the issue with python 3.13+ support and the discussion doesn’t seem to be around how to do it but if it should be done/prioritized in the first place.

to be honest, it looks like you’re a bot and that was chatgpt.

**Comment by HansBug** [comment]
fixed in #112 

a new released is here: https://github.com/HansBug/hbutils/releases/tag/v0.11.0 @aubreyyan @chef88314 

this issue will be closed, if you guys find more issues about this, plz reopen it.
